name: Updates after PR merge
on:
  push:
    branches: [ main ]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  Migrations:
    name: Run DB Migrations
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Setup - Checkout code
      uses: actions/checkout@v1

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

    - name: Push migrations (production)
      run: DATABASE_URL=${{ secrets.DATABASE_URL }} npx prisma migrate deploy
