name: Portfolio CI
on:
  pull_request:
    branches: [ main ]
jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      SAFE_BROWSING_API_KEY: ${{ secrets.SAFE_BROWSING_API_KEY }}

    steps:
    - name: Setup - Checkout
      uses: actions/checkout@v1

    - name: Start API and DB containers
      run: docker-compose -f docker-compose.ci.yml up -d --build --remove-orphans --force-recreate

    - name: "Lint"
      run: "docker-compose -f docker-compose.ci.yml exec -T app npm run lint"

    - name: "Unit Tests"
      run: "docker-compose -f docker-compose.ci.yml exec -T app npm run test"

    - name: Migrate database
      run: docker-compose -f docker-compose.ci.yml exec -T app npm run db:migrate

    - name: Seed database
      run: docker-compose -f docker-compose.ci.yml exec -T app npm run db:seed

    - name: Integration Tests
      run: docker-compose -f docker-compose.ci.yml exec -T -e TEST_COMMAND=run app npm run cypress

    - name: Stop containers
      if: always()
      run: docker-compose -f docker-compose.ci.yml down
