name: Daily Cron Jobs
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  clean-links:
    runs-on: ubuntu-latest
    env:
      SAFE_BROWSING_API_KEY: ${{ secrets.SAFE_BROWSING_API_KEY }}
      DATABASE_URL: ${{ secrets.PRODUCTION_DB_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run clean-urls
